apiVersion: apps/v1
kind: Deployment
metadata:
  name: druid-zookeeper
  namespace: druid
  labels:
    component: druid-zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      component: druid-zookeeper
  template:
    metadata:
      labels:
        component: druid-zookeeper
    spec:
      containers:
        - name: druid-zookeeper
          image: zookeeper:3.4.14
          imagePullPolicy: IfNotPresent
          ports:
            - name: client
              containerPort: 2181
              protocol: TCP
            - name: election
              containerPort: 3888
              protocol: TCP
            - name: server
              containerPort: 2888
              protocol: TCP