apiVersion: v1
kind: Service
metadata:
  name: druid-middlemanager
  namespace: druid
  labels:
    component: middlemanager
spec:
  type: ClusterIP
  ports:
    - port: 8091
      targetPort: http
      protocol: TCP
      name: http
  selector:
    component: middlemanager