apiVersion: v1
kind: Service
metadata:
  name: druid-overlord
  namespace: druid
  labels:
    component: overlord
spec:
  type: ClusterIP
  ports:
    - port: 8090
      targetPort: http
      protocol: TCP
      name: http
  selector:
    component: overlord
