apiVersion: v1
kind: Service
metadata:
  name: druid-router
  namespace: druid
  labels:
    component: router
spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: http
      protocol: TCP
      name: http
  selector:
    component: router
